# Generated by Django 4.0.6 on 2022-09-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('team', models.CharField(max_length=50, unique=True)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
