# Generated by Django 4.0.6 on 2022-09-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_player_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='votes',
        ),
        migrations.AddField(
            model_name='player',
            name='mean_value',
            field=models.FloatField(default=0),
        ),
    ]
