# Generated by Django 4.0.6 on 2022-09-02 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_player_votes_player_mean_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='mean_value',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
