# Generated by Django 4.1 on 2022-09-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bid_created_at_bid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
