# Generated by Django 4.1 on 2022-09-03 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='guestCanSee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='week',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(17)]),
            preserve_default=False,
        ),
    ]
