# Generated by Django 4.1 on 2022-09-04 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_player_guestcansee_remove_player_mean_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='player',
        ),
        migrations.AddField(
            model_name='bid',
            name='target',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='api.target'),
            preserve_default=False,
        ),
    ]
