# Generated by Django 4.1 on 2022-09-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_bid_player_bid_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
