# Generated by Django 4.1 on 2022-09-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_player_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='mean_value',
        ),
    ]
