# Generated by Django 4.1 on 2022-09-07 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_position_team_alter_player_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='week',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(17)]),
        ),
    ]
