# Generated by Django 4.1 on 2023-08-22 11:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_player_image_player_link_alter_player_position_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(null=True, max_length=4, unique=True),
            preserve_default=False,
        ),
       
    ]
