# Generated by Django 4.1 on 2023-09-26 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_player_image_player_link_ranking_opponent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='week',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='target',
            name='week',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
