# Generated by Django 4.1 on 2023-09-26 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_ranking_week_alter_target_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='week',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
