# Generated by Django 4.1 on 2024-06-13 10:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_bid_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='target',
        ),
        migrations.AddField(
            model_name='bid',
            name='Player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='api.player'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BidOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('week', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)])),
                ('user', models.CharField(max_length=50)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='api.target')),
            ],
        ),
    ]
