# Generated by Django 4.1 on 2024-06-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_bid_target_bid_player_bidoriginal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='Player',
            new_name='player',
        ),
    ]
