# Generated by Django 4.1 on 2024-08-20 12:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_player_bid_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_rankings', to='api.player')),
            ],
        ),
    ]
