# Generated by Django 4.1 on 2024-08-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
