# Generated by Django 5.1.2 on 2026-08-29 21:46

import api.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_player_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('crowd', 'Crowd'), ('market', 'Market')], max_length=8)),
                ('season', models.IntegerField()),
                ('week', models.IntegerField()),
                ('league_size', models.IntegerField(default=0)),
                ('scoring', models.CharField(choices=[('all', 'All formats'), ('ppr', 'PPR'), ('half', 'Half PPR'), ('std', 'Standard')], default='all', max_length=8)),
                ('counts', models.JSONField(default=api.models.zero_counts)),
                ('won_counts', models.JSONField(default=api.models.zero_counts)),
                ('n', models.IntegerField(default=0)),
                ('n_leagues', models.IntegerField(default=0)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('mode', models.IntegerField(blank=True, null=True)),
                ('p25', models.FloatField(blank=True, null=True)),
                ('p75', models.FloatField(blank=True, null=True)),
                ('min_bid', models.IntegerField(blank=True, null=True)),
                ('max_bid', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=32, unique=True)),
                ('sleeper_player_id', models.CharField(db_index=True, max_length=16)),
                ('season', models.IntegerField()),
                ('week', models.IntegerField()),
                ('bid_raw', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('bid_pct', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('won', models.BooleanField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SleeperLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.CharField(max_length=32, unique=True)),
                ('season', models.IntegerField(db_index=True)),
                ('total_rosters', models.IntegerField(default=0)),
                ('waiver_budget', models.IntegerField(default=100)),
                ('waiver_type', models.IntegerField(default=2)),
                ('waiver_day', models.IntegerField(blank=True, null=True)),
                ('scoring', models.CharField(choices=[('all', 'All formats'), ('ppr', 'PPR'), ('half', 'Half PPR'), ('std', 'Standard')], default='std', max_length=8)),
                ('ppr_value', models.FloatField(default=0.0)),
                ('previous_league_id', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_ingested_week', models.IntegerField(default=0)),
                ('empty_week_streak', models.IntegerField(default=0)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='submitter',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='sleeper_id',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['week', 'player'], name='bid_week_player_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['name'], name='player_name_idx'),
        ),
        migrations.AddIndex(
            model_name='ranking',
            index=models.Index(fields=['week', 'Player'], name='ranking_week_player_idx'),
        ),
        migrations.AddIndex(
            model_name='ranking',
            index=models.Index(fields=['week', 'user'], name='ranking_week_user_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['week', 'player'], name='target_week_player_idx'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(condition=models.Q(('submitter__isnull', False)), fields=('player', 'week', 'submitter'), name='uniq_bid_per_submitter_player_week'),
        ),
        migrations.AddField(
            model_name='bidaggregate',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='api.player'),
        ),
        migrations.AddField(
            model_name='marketbid',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_bids', to='api.player'),
        ),
        migrations.AddIndex(
            model_name='sleeperleague',
            index=models.Index(fields=['season', 'is_active'], name='league_season_active_idx'),
        ),
        migrations.AddField(
            model_name='marketbid',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_bids', to='api.sleeperleague'),
        ),
        migrations.AddIndex(
            model_name='bidaggregate',
            index=models.Index(fields=['scope', 'season', 'week', 'league_size', 'scoring'], name='agg_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='bidaggregate',
            constraint=models.UniqueConstraint(fields=('scope', 'player', 'season', 'week', 'league_size', 'scoring'), name='uniq_aggregate_slice'),
        ),
        migrations.AddIndex(
            model_name='marketbid',
            index=models.Index(fields=['season', 'week', 'sleeper_player_id'], name='market_swp_idx'),
        ),
        migrations.AddIndex(
            model_name='marketbid',
            index=models.Index(fields=['season', 'week', 'player'], name='market_swplayer_idx'),
        ),
    ]
