# Generated by Django 5.1.2 on 2026-09-14 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_bidaggregate_marketbid_sleeperleague_bid_submitter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What this key is for.', max_length=120)),
                ('email', models.EmailField(blank=True, help_text='Where to reach the owner.', max_length=254)),
                ('prefix', models.CharField(db_index=True, max_length=12, unique=True)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('tier', models.CharField(choices=[('anon', 'Anonymous (no key)'), ('free', 'Free'), ('hobby', 'Hobby'), ('pro', 'Pro')], default='free', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['key_hash', 'is_active'], name='apikey_lookup_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(blank=True, db_index=True, max_length=45)),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('calls', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='api.apikey')),
            ],
            options={
                'indexes': [models.Index(fields=['period'], name='usage_period_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('key__isnull', False)), fields=('key', 'period'), name='uniq_usage_key_period'), models.UniqueConstraint(condition=models.Q(('key__isnull', True)), fields=('client_ip', 'period'), name='uniq_usage_ip_period')],
            },
        ),
    ]
