# Generated by Django 5.1.2 on 2026-09-15 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_apikey_apiusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='nfl_week',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)]),
        ),
        migrations.AddField(
            model_name='target',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='trending_adds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='trending_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['season', 'nfl_week'], name='target_season_week_idx'),
        ),
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(condition=models.Q(('season__isnull', False)), fields=('player', 'season', 'nfl_week'), name='uniq_target_player_season_week'),
        ),
    ]
